# Numpy

__Numpy__ is a _Python package_ that stands for ___Numerical Python___. It is a _library_ for the _Python_ programming language, adding support for large, _multi-dimensional arrays_ and _matrices_, along with a _large collection_ of high-level mathematical functions to operate on these _arrays_.

__Numpy__ provides a powerful _N-dimensional_ array object, useful for performing mathematical and logical operations on arrays. It also has _functions_ for working in domain of _linear algebra_, _Fourier transform_, and _matrices_.

By importing `numpy as np`, we can access all the functions and methods provided by the _numpy_ package using the `np` alias.

In [41]:
#seleccionar kernel entorno
import numpy as np
# create an array
array_1 = np.array([1,2,3,4,5,6,7,8,6,4,3,2,1,1,2,7,8])
print('Part 1:', array_1, type(array_1))
print('-'*30)
# create an array with range
array = np.array(range(10,51,2))
print('Part 2:', array, type(array))

array = np.arange(10,51,2)
print('Part 2:', array, type(array))
print('-'*30)
# create an array with linspace
array = np.linspace(0,1,25)
print('Part 3:', array)
print('-'*30)
# create a matrix of zeros
zeros = np.zeros((3,4))
print('Part 4:\n', zeros)
ones = np.ones((3,3))
print('Part 4.1:\n', ones)
print('-'*30)
# get array data type
print('DATA TYPES')
print(array_1.dtype)
print(array.dtype)
print(zeros.dtype)

Part 1: [1 2 3 4 5 6 7 8 6 4 3 2 1 1 2 7 8] <class 'numpy.ndarray'>
------------------------------
Part 2: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
Part 2: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
------------------------------
Part 3: [0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]
------------------------------
Part 4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Part 4.1:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
DATA TYPES
int64
float64
float64


In [28]:
# get shape of array
print('Part 1:',array.shape)
print('-'*30)
# get shape of matrix
print('Part 2:', zeros.shape)
print('-'*30)
# get number of dimensions of array
print('Part 3:',array.ndim)
print('-'*30)
# get number of dimensions of matrix
print('Part 4:', zeros.ndim)

Part 1: (11,)
------------------------------
Part 2: (3, 4)
------------------------------
Part 3: 1
------------------------------
Part 4: 2


In [33]:
# get number of elements in array
length = array.size
print('Part 1:',length, type(length))
print('-'*30)
# get element by index
element_array = array[4]
print('Part 2:', element_array)
element_matrix = zeros[1,2]
print('Part 2.1:',element_matrix)

Part 1: 11 <class 'int'>
------------------------------
Part 2: 0.4
Part 2.1: 0.0


In [43]:
# descriptive statistics
# get sum of array
sum = array.sum()
print('Sum:',sum)

# get mean of array
mean = array.mean()
print('Mean:',mean)

# get standard deviation of array
standard_deviation = array.std()
print('Standard Deviation:',standard_deviation)

# get variance of array
variance = array.var()
print('Variance:',variance)

# get min of array
min = array.min()
print('Minimum:',min)

# get max of array
max = array.max()
print('Maximum:',max)

Sum: 12.5
Mean: 0.5
Standard Deviation: 0.3004626062886657
Variance: 0.09027777777777776
Minimum: 0.0
Maximum: 1.0


In [47]:
# slice a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n',matrix)

slice = matrix[:2,1:]
print('Slice:\n',slice)

# is the slice by reference or by value?


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slice:
 [[2 3]
 [5 6]]


## Linear Algebra with Numpy

_Numpy_ is a powerful _Python_ package that provides support for _linear algebra_ operations. It allows us to perform various mathematical operations on _arrays_ and _matrices_ efficiently.

With __Numpy__, we can easily solve _linear algebra_ problems such as finding solutions to systems of linear equations, calculating matrix determinants, eigenvalues, eigenvectors, and much more.

# 

In [55]:
# solve a system of linear equations
equations = np.array([[2,3],[3,7]])
answers = np.array([5,12])
solution = np.linalg.solve(equations,answers)
print('Solution:',solution)

Solution: [-0.2  1.8]


In [59]:
# get the inverse of a matrix
inv = np.linalg.inv(equations)
print('Inverse:',inv)


Inverse: [[ 1.4 -0.6]
 [-0.6  0.4]]


In [58]:
# get the determinant of a matrix
det = np.linalg.det(equations)
print('Determinant:',np.round(det))

Determinant: 5.0


In [60]:
# get the dot product of two arrays
array_2 = np.array([1,2,3])
array_3 = np.array([4,5,6])
print('Dot:', np.dot(array_2,array_3))

Dot: 32


In [61]:
# get the cross product of two arrays
#Cross = [2*6-3*5 3*4-1*6 1*5-2*4]
print('Cross:',np.cross(array_2,array_3))

Cross: [-3  6 -3]


In [62]:
# get the norm of an array
print('Norm:',np.linalg.norm(array_2))

Norm: 3.7416573867739413


In [67]:
# get the eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(equations)
print('Eigenvalues:', eigenvalues)
print('Eigenvector:',eigenvectors)

Eigenvalues: [0.59487516 8.40512484]
Eigenvector: [[-0.90558942 -0.4241554 ]
 [ 0.4241554  -0.90558942]]


## Vectorization

__Vectorization__ is a technique in computer programming that allows us to perform operations on _entire arrays or matrices_ instead of looping through each element individually. This approach leverages the power of optimized, low-level operations provided by libraries like __NumPy__.

By using _vectorized operations_, we can significantly improve the _performance_ of our code, as it takes advantage of parallel processing capabilities of modern _CPUs_. Instead of writing explicit loops, we can express our computations as _mathematical expressions_ on arrays, making our code more concise and readable.

For example, instead of iterating over each element of an array to calculate the square root, we can simply apply the `np.sqrt()` function to the _entire array_. This not only simplifies the code but also improves its efficiency.

In addition to arithmetic operations, __vectorization__ also enables us to perform logical operations, mathematical functions, and other operations on arrays and matrices. This makes it a powerful tool for _scientific computing_, _data analysis_, and _machine learning_ tasks.

Overall, __vectorization__ is a fundamental concept in array programming that allows us to write efficient and concise code by operating on entire arrays or matrices at once. It is a key technique to leverage the full potential of libraries like __NumPy__ and optimize our computations.

In [69]:
import memory_profiler
import time

# decorator to time a function
def time_function(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Time taken: {end - start}")
        return result
    return wrapper

# decorator to get memory usage of a function
def memory_function(func):
    def wrapper(*args, **kwargs):
        result = memory_profiler.memory_usage((func, args, kwargs))
        print(f"Memory used: {result[0]}")
        return result
    return wrapper

In [75]:
# calculare the square root of a matrix with vertorization
@time_function
@memory_function
def sqrt_vectorized(matrix):
    return np.sqrt(matrix)

# calculate the square root of a matrix with a loop
@time_function
@memory_function
def sqrt_loop(matrix):
    result = np.zeros_like(matrix)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i,j] = np.sqrt(matrix[i,j])

    return result

#-------Test----------
size = 10000
matrix = np.random.rand(size,size)
#print('Matrix\n',matrix)
print('Shape:', matrix.shape)
print('Vectorized')
t = sqrt_vectorized(matrix.copy())
print('Loop')
t = sqrt_loop(matrix.copy())

Shape: (10000, 10000)
Vectorized
Memory used: 1628.77734375
Time taken: 2.09902024269104
Loop
Memory used: 1628.77734375
Time taken: 149.53760838508606


In [ ]:
# calculate the sum of two arrays witn vectorization


# calculate the sum of two arrays with a loop


In [ ]:
# calculate broadcasted multiplication of and array and a scalar with vectorization


# calculate broadcasted multiplication of and array and a scalar with a loop


In [ ]:
# filter an array with vectorization


# filter an array with a loop


# filter an array with a lambda function

# Strings

A __string__ is a _sequence of characters_ enclosed in single quotes ( `''`) or double quotes (`""`).

In __Python__, strings are _immutable_, which means they cannot be changed once created.

__Strings__ can be _concatenated_ using the `+` operator, and _repeated_ using the `*` operator.

Various _string_ methods are available to perform operations like finding the _length_, _converting case_, _splitting_, and _joining_ strings.

In [ ]:
# compare strings using conditionals


In [ ]:
# check if a substring is in a string


In [ ]:
# traverse a string with a loop


In [ ]:
# get length of a string


# concatenate strings


# repeat a string


In [ ]:
# format using format method


# format using f-strings


In [ ]:
# split a string


# join a list of strings


In [ ]:
# replace a substring


# find the index of a substring


# count occurrences of a substring


# DateTimes

__Datetimes__ in _Python_ are objects that represent _dates_ and _times_. They are used to perform various operations related to dates and times, such as _calculating time differences_, _formatting dates_, and _parsing strings_ into datetime objects.


In [ ]:
# Create a datetime object representing the current date and time


# Create a date object representing a specific date


# Create a time object representing a specific time


# Get the current datetime with a specific timezone



In [ ]:
# Use strftime to format a date and time


# Use strptime to parse a date and time string


In [ ]:
# Timedelta object representing the difference between two dates and times


# Regular Expressions

__Regular expressions__, also known as __regex__, are powerful tools for _pattern matching_ and _text manipulation_ in Python. They allow you to search, match, and manipulate strings based on specific __patterns__.

In _Python_, regular expressions are supported through the `re` module. This module provides functions and methods for working with regular expressions.

To use __regular expressions__ in _Python_, you need to import the `re` module. Once imported, you can use various functions and methods provided by the module to perform operations such as _pattern matching_, _searching_, _replacing_, and _splitting strings_.

__Regular expressions__ in _Python_ are defined using a combination of special characters and metacharacters that represent _patterns_. 

In [ ]:
# use regex to find a substring


# use regex to find all substrings


In [ ]:
# use regex to find all words starting with a specific letter


# use regex to find numbers in a string


In [ ]:
# use regex to replace a substring


# use regex to split a string


In [ ]:
# use regex to match a string


# use regex to find all posibilities of a pattern


In [ ]:
# validate an email address
