# Numpy

__Numpy__ is a _Python package_ that stands for ___Numerical Python___. It is a _library_ for the _Python_ programming language, adding support for large, _multi-dimensional arrays_ and _matrices_, along with a _large collection_ of high-level mathematical functions to operate on these _arrays_.

__Numpy__ provides a powerful _N-dimensional_ array object, useful for performing mathematical and logical operations on arrays. It also has _functions_ for working in domain of _linear algebra_, _Fourier transform_, and _matrices_.

By importing `numpy as np`, we can access all the functions and methods provided by the _numpy_ package using the `np` alias.

In [4]:
#seleccionar kernel entorno
import numpy as np
# create an array
array_1 = np.array([1,2,3,4,5,6,7,8,6,4,3,2,1,1,2,7,8])
print('Part 1:', array_1, type(array_1))
print('-'*30)
# create an array with range
array = np.array(range(10,51,2))
print('Part 2:', array, type(array))

array = np.arange(10,51,2)
print('Part 2:', array, type(array))
print('-'*30)
# create an array with linspace
array = np.linspace(0,1,25)
print('Part 3:', array)
print('-'*30)
# create a matrix of zeros
zeros = np.zeros((3,4))
print('Part 4:\n', zeros)
ones = np.ones((3,3))
print('Part 4.1:\n', ones)
print('-'*30)
# get array data type
print('DATA TYPES')
print(array_1.dtype)
print(array.dtype)
print(zeros.dtype)

Part 1: [1 2 3 4 5 6 7 8 6 4 3 2 1 1 2 7 8] <class 'numpy.ndarray'>
------------------------------
Part 2: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
Part 2: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] <class 'numpy.ndarray'>
------------------------------
Part 3: [0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]
------------------------------
Part 4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Part 4.1:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
DATA TYPES
int64
float64
float64


In [28]:
# get shape of array
print('Part 1:',array.shape)
print('-'*30)
# get shape of matrix
print('Part 2:', zeros.shape)
print('-'*30)
# get number of dimensions of array
print('Part 3:',array.ndim)
print('-'*30)
# get number of dimensions of matrix
print('Part 4:', zeros.ndim)

Part 1: (11,)
------------------------------
Part 2: (3, 4)
------------------------------
Part 3: 1
------------------------------
Part 4: 2


In [33]:
# get number of elements in array
length = array.size
print('Part 1:',length, type(length))
print('-'*30)
# get element by index
element_array = array[4]
print('Part 2:', element_array)
element_matrix = zeros[1,2]
print('Part 2.1:',element_matrix)

Part 1: 11 <class 'int'>
------------------------------
Part 2: 0.4
Part 2.1: 0.0


In [43]:
# descriptive statistics
# get sum of array
sum = array.sum()
print('Sum:',sum)

# get mean of array
mean = array.mean()
print('Mean:',mean)

# get standard deviation of array
standard_deviation = array.std()
print('Standard Deviation:',standard_deviation)

# get variance of array
variance = array.var()
print('Variance:',variance)

# get min of array
min = array.min()
print('Minimum:',min)

# get max of array
max = array.max()
print('Maximum:',max)

Sum: 12.5
Mean: 0.5
Standard Deviation: 0.3004626062886657
Variance: 0.09027777777777776
Minimum: 0.0
Maximum: 1.0


In [47]:
# slice a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matrix:\n',matrix)

slice = matrix[:2,1:]
print('Slice:\n',slice)

# is the slice by reference or by value?


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slice:
 [[2 3]
 [5 6]]


## Linear Algebra with Numpy

_Numpy_ is a powerful _Python_ package that provides support for _linear algebra_ operations. It allows us to perform various mathematical operations on _arrays_ and _matrices_ efficiently.

With __Numpy__, we can easily solve _linear algebra_ problems such as finding solutions to systems of linear equations, calculating matrix determinants, eigenvalues, eigenvectors, and much more.

# 

In [55]:
# solve a system of linear equations
equations = np.array([[2,3],[3,7]])
answers = np.array([5,12])
solution = np.linalg.solve(equations,answers)
print('Solution:',solution)

Solution: [-0.2  1.8]


In [59]:
# get the inverse of a matrix
inv = np.linalg.inv(equations)
print('Inverse:',inv)


Inverse: [[ 1.4 -0.6]
 [-0.6  0.4]]


In [58]:
# get the determinant of a matrix
det = np.linalg.det(equations)
print('Determinant:',np.round(det))

Determinant: 5.0


In [60]:
# get the dot product of two arrays
array_2 = np.array([1,2,3])
array_3 = np.array([4,5,6])
print('Dot:', np.dot(array_2,array_3))

Dot: 32


In [61]:
# get the cross product of two arrays
#Cross = [2*6-3*5 3*4-1*6 1*5-2*4]
print('Cross:',np.cross(array_2,array_3))

Cross: [-3  6 -3]


In [62]:
# get the norm of an array
print('Norm:',np.linalg.norm(array_2))

Norm: 3.7416573867739413


In [67]:
# get the eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(equations)
print('Eigenvalues:', eigenvalues)
print('Eigenvector:',eigenvectors)

Eigenvalues: [0.59487516 8.40512484]
Eigenvector: [[-0.90558942 -0.4241554 ]
 [ 0.4241554  -0.90558942]]


## Vectorization

__Vectorization__ is a technique in computer programming that allows us to perform operations on _entire arrays or matrices_ instead of looping through each element individually. This approach leverages the power of optimized, low-level operations provided by libraries like __NumPy__.

By using _vectorized operations_, we can significantly improve the _performance_ of our code, as it takes advantage of parallel processing capabilities of modern _CPUs_. Instead of writing explicit loops, we can express our computations as _mathematical expressions_ on arrays, making our code more concise and readable.

For example, instead of iterating over each element of an array to calculate the square root, we can simply apply the `np.sqrt()` function to the _entire array_. This not only simplifies the code but also improves its efficiency.

In addition to arithmetic operations, __vectorization__ also enables us to perform logical operations, mathematical functions, and other operations on arrays and matrices. This makes it a powerful tool for _scientific computing_, _data analysis_, and _machine learning_ tasks.

Overall, __vectorization__ is a fundamental concept in array programming that allows us to write efficient and concise code by operating on entire arrays or matrices at once. It is a key technique to leverage the full potential of libraries like __NumPy__ and optimize our computations.

In [2]:
import memory_profiler
import time

# decorator to time a function
def time_function(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Time taken: {end - start}")
        return result
    return wrapper

# decorator to get memory usage of a function
def memory_function(func):
    def wrapper(*args, **kwargs):
        result = memory_profiler.memory_usage((func, args, kwargs))
        print(f"Memory used: {result[0]}")
        return result
    return wrapper

In [75]:
# calculare the square root of a matrix with vertorization
@time_function
@memory_function
def sqrt_vectorized(matrix):
    return np.sqrt(matrix)

# calculate the square root of a matrix with a loop
@time_function
@memory_function
def sqrt_loop(matrix):
    result = np.zeros_like(matrix)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i,j] = np.sqrt(matrix[i,j])

    return result

#-------Test----------
size = 10000
matrix = np.random.rand(size,size)
#print('Matrix\n',matrix)
print('Shape:', matrix.shape)
print('Vectorized')
t = sqrt_vectorized(matrix.copy())
print('Loop')
t = sqrt_loop(matrix.copy())

Shape: (10000, 10000)
Vectorized
Memory used: 1628.77734375
Time taken: 2.09902024269104
Loop
Memory used: 1628.77734375
Time taken: 149.53760838508606


In [11]:
# calculate the sum of two arrays witn vectorization
@time_function
@memory_function
def sum_vectorized(array_1:np.array,array_2:np.array):
    return array_1 + array_2


# calculate the sum of two arrays with a loop
@time_function
@memory_function
def sum_loops(array_1, array_2):
    result = np.zeros_like(array_1)
    for i in range(array_1.size):
        result[i] = array_1[i] + array_2[i]
    return result
#-----------Test------------
size = 100000000
array_1 = np.random.rand(size)
array_2 = np.random.rand(size)
print('Shape:',array_1.shape, array_2.shape)
print('Vectorized')
t = sum_vectorized(array_1, array_2)
print('Loops')
t = sum_loops(array_1, array_2)

Shape: (100000000,) (100000000,)
Vectorized
Memory used: 3583.96484375
Time taken: 2.352979898452759
Loops
Memory used: 3584.5
Time taken: 36.995707273483276


In [14]:
# calculate broadcasted multiplication of and array and a scalar with vectorization
@time_function
@memory_function
def broadcasted_vectorized(array:np.array, scalar:int):
    return array * scalar
# calculate broadcasted multiplication of and array and a scalar with a loop
@time_function
@memory_function
def broadcasted_loop(array:np.array, scalar:int):
    result = np.zeros_like(array)
    for i in range(array.size):
        result[i] = array[i] * scalar
    return result

#-------Test-------
size = 100000000
array = np.random.rand(size)
scalar = np.random.randint(1,10)
print('Shape:', array.shape, " --Scalar:",scalar)
print('Vectorized')
t = broadcasted_vectorized(array,scalar)
print('Loops')
t = broadcasted_loop(array,scalar)

Shape: (100000000,)  --Scalar: 6
Vectorized
Memory used: 3390.45703125
Time taken: 1.837761402130127
Loops
Memory used: 3390.46484375
Time taken: 30.74987769126892


In [16]:
# filter an array with a loop
@time_function
@memory_function
def is_even_vectorized(array):
    return array[array % 2 == 0] #boolean mask, when true, the value passes, when false, the values does not pass

# filter an array with a lambda function
@time_function
@memory_function
def is_even_lambda(array):
    return list(filter(lambda x: x%2==0, array))

#loops
@time_function
@memory_function
def is_even_loop(array):
    result = []
    for x in array:
        if x % 2 == 0:
            result.append(x)
    return result

#----------Test-------------
size = 100000000
array = np.random.rand(size)
print('Vectorized')
t = is_even_vectorized(array)
print('Lambda:')
t = is_even_lambda(array)
print('Loop')
t = is_even_loop(array)

Vectorized
Memory used: 2751.22265625
Time taken: 4.861858367919922
Lambda:
Memory used: 2751.22265625
Time taken: 28.365644931793213
Loop
Memory used: 2751.22265625
Time taken: 23.659568309783936


# Strings

A __string__ is a _sequence of characters_ enclosed in single quotes ( `''`) or double quotes (`""`).

In __Python__, strings are _immutable_, which means they cannot be changed once created.

__Strings__ can be _concatenated_ using the `+` operator, and _repeated_ using the `*` operator.

Various _string_ methods are available to perform operations like finding the _length_, _converting case_, _splitting_, and _joining_ strings.

In [17]:
# compare strings using conditionals
s_1 = 'hello'
s_2 = 'ud'
if s_1 == s_2:
    print('Equal')
if s_1 != s_2:
    print('NOT Equal')
if s_1 < s_2:
    print(s_1, 'Less than', s_2)

NOT Equal
hello Less than ud


In [20]:
# check if a substring is in a string
sub = 'ell'
if sub in s_1:
    print('Substring found.')
else:
    print('NOT FOUND.')

Substring found.


In [21]:
# traverse a string with a loop
for character in s_1:
    print(character)

h
e
l
l
o


In [26]:
# get length of a string
print('Length of a string')
print(len(s_1))

# concatenate strings
print('Strings Concatenated')
print(s_1 + s_2)
print(s_2 + s_1)
print(s_1 + " " + s_2)

# repeat a string
print('String repeated')
print(s_1*10)

Length of a string
5
Strings Concatenated
helloud
udhello
hello ud
String repeated
hellohellohellohellohellohellohellohellohellohello


In [28]:
name = 'Lupita'
# format using format method
print('Que le pasa a {}?'.format(name))

# format using f-strings
print(f'Que le pasa a {name}?')

Que le pasa a Lupita?
Que le pasa a Lupita?


In [34]:
# split a string
name = 'Nico Jorge Ana Ricardo Muller Messi Gerd Gerard'
splitted_name = name.split(' ')
print(splitted_name)

# join a list of strings
joined_names = ', '.join(splitted_name)
print(joined_names)

['Nico', 'Jorge', 'Ana', 'Ricardo', 'Muller', 'Messi', 'Gerd', 'Gerard']
Nico, Jorge, Ana, Ricardo, Muller, Messi, Gerd, Gerard


In [40]:
# replace a substring
print('Replace:', joined_names.replace('i','iGOD'))


# find the index of a substring
s_3 = s_1 * 3
print(s_3)
print('Index:', s_3.find('el'))

# count occurrences of a substring
print('Count a:', joined_names.count('a'))
print('Count M:', joined_names.count('M'))

#Cases
print('Lower case:', joined_names.lower())
print('Upper Cases:', joined_names.upper())
print('Title Cases:', joined_names.title())
print('Swap Cases:', joined_names.swapcase())

Replace: NiGODco, Jorge, Ana, RiGODcardo, Muller, MessiGOD, Gerd, Gerard
hellohellohello
Index: 1
Count a: 3
Count M: 2
Lower case: nico, jorge, ana, ricardo, muller, messi, gerd, gerard
Upper Cases: NICO, JORGE, ANA, RICARDO, MULLER, MESSI, GERD, GERARD
Title Cases: Nico, Jorge, Ana, Ricardo, Muller, Messi, Gerd, Gerard
Swap Cases: nICO, jORGE, aNA, rICARDO, mULLER, mESSI, gERD, gERARD


# DateTimes

__Datetimes__ in _Python_ are objects that represent _dates_ and _times_. They are used to perform various operations related to dates and times, such as _calculating time differences_, _formatting dates_, and _parsing strings_ into datetime objects.


In [57]:
from datetime import datetime as jueputaQueAburrimiento
# Create a datetime object representing the current date and time
current = jueputaQueAburrimiento.now()
print('Now:',current)

# Create a date object representing a specific date
date_1 = jueputaQueAburrimiento(year=2016, month=6, day=9)
print('Date 1:',date_1)

# Create a time object representing a specific time
print('Time:', jueputaQueAburrimiento.time(current))

# Get the current datetime with a specific timezone
from pytz import timezone
colombia_tz = timezone('America/Bogota')
current_colombia = jueputaQueAburrimiento.now(colombia_tz)
print('Now in Colombia:', current_colombia)


Now: 2024-06-26 10:40:20.404327
Date 1: 2016-06-09 00:00:00
Time: 10:40:20.404327
Now in Colombia: 2024-06-26 10:40:20.404327-05:00


In [53]:
# Use strftime to format a date and time
print('Format y-m(letter)-d h-m-s:', current_colombia.strftime("%Y-%b-%d %H-%M-%S"))
print('Format d(letter), m(letter), d(num), y:', current_colombia.strftime("%A, %b, %d"))

# Use strptime to parse a date and time string
date_string = "2023-02-21"
date_2 = jueputaQueAburrimiento.strptime(date_string, "%Y-%m-%d")
print('Date 2:', type(date_2), date_2)

Format y-m(letter)-d h-m-s: 2024-Jun-26 10-28-55
Format d(letter), m(letter), d(num), y: Wednesday, Jun, 26
Date 2: <class 'datetime.datetime'> 2023-02-21 00:00:00


In [58]:
# Timedelta object representing the difference between two dates and times
from datetime import timedelta
print('Tomorrow:', current_colombia + timedelta(days=1))
print('Yesterday:', current_colombia - timedelta(days=1))
print('Deadline:', current_colombia + timedelta(minutes=60))

Tomorrow: 2024-06-27 10:40:20.404327-05:00
Yesterday: 2024-06-25 10:40:20.404327-05:00
Deadline: 2024-06-26 11:40:20.404327-05:00


# Regular Expressions

__Regular expressions__, also known as __regex__, are powerful tools for _pattern matching_ and _text manipulation_ in Python. They allow you to search, match, and manipulate strings based on specific __patterns__.

In _Python_, regular expressions are supported through the `re` module. This module provides functions and methods for working with regular expressions.

To use __regular expressions__ in _Python_, you need to import the `re` module. Once imported, you can use various functions and methods provided by the module to perform operations such as _pattern matching_, _searching_, _replacing_, and _splitting strings_.

__Regular expressions__ in _Python_ are defined using a combination of special characters and metacharacters that represent _patterns_. 

In [62]:
import re
# use regex to find a substrings
string = "hello world, ud summer vacations sapo salome"
substring = "world,"
if re.search(substring, string):
    print('Substring found')
else:
    print('NOT FOUND.')

# use regex to find all substrings
words = re.findall(r'\w+', string)
print('Words:', words)

words_s = re.findall(r'\b[s]\w+', string)
print('Words starting with s:', words_s)

Substring found
Words: ['hello', 'world', 'ud', 'summer', 'vacations', 'sapo', 'salome']
Words starting with s: ['summer', 'sapo', 'salome']


In [ ]:
# use regex to find all words starting with a specific letter


# use regex to find numbers in a string


In [66]:
string_num = "Your ID is 89"
# use regex to replace a substring
print('Replace:', re.sub(r'ud', "Universidad Distrital", string))
print('Replace Numbers:', re.sub(r'\d+', "XX", string_num))

# use regex to split a string
print('Words:', re.split(r'\d+', string_num))

Replace: hello world, Universidad Distrital summer vacations sapo salome
Replace Numbers: Your ID is XX
Words: ['Your ID is ', '']


In [70]:
# use regex to match a string
if re.match(r'^[ell]$', string):
    print('Pattern FOUND')
else:
    print('NOT FOUND')

# use regex to find all posibilities of a pattern
string = 'skjdfadsjfkasjdjfjsdkfjlkasjfodjklj fjadsfkfkasj jdsakfjkasj'
pattern = '[a-d]'
print('Matchers:', re.findall(pattern,string))

pattern = '[d][j-l]'
print('Matches:', re.findall(pattern,string))


NOT FOUND
Matchers: ['d', 'a', 'd', 'a', 'd', 'd', 'a', 'd', 'a', 'd', 'a', 'd', 'a', 'a']
Matches: ['dj', 'dk', 'dj']


In [78]:
# validate an email address
email = 'test.a2_class@udistrital.edu.co'
pattern = r'^[a-z][a-z0-9._]*@udistrital.edu.co$'
if re.match(pattern, email):
    print('VALID EMAIL')
else:
    print('INVALID')

VALID EMAIL
